apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: roles
  version: default
  rules:

  - actions: [ create, update, archive, delete ]
    effect: EFFECT_ALLOW
    roles: [ owner, manager ]
    condition:
      match:
        expr: R.attr.company_id == P.attr.company_id

  - actions: [ view, list ]
    effect: EFFECT_ALLOW
    roles: [ '*' ]
    condition:
      match:
        any:
          of:
          - expr: R.attr.company_id == P.attr.company_id
          - expr: R.attr.company_id == null
