auth_enabled: false

server:
  http_listen_port: 3100

limits_config:
  retention_period: 30d
schema_config:
  configs:
  - from: 2023-01-01
    store: tsdb
    object_store: s3
    schema: v13
    index:
      prefix: index_
      period: 24h
common:
  path_prefix: /loki
  replication_factor: 1
  compactor_address: http://loki:3100
  storage:
    s3:
      insecure: false
      endpoint: ${S3_ENDPOINT}
      bucketnames: ${S3_NAME}
      access_key_id: ${S3_ACCESS_KEY}
      secret_access_key: ${S3_SECRET}
      s3forcepathstyle: true
  ring:
    kvstore:
      store: inmemory
ruler:
  storage:
    s3:
      bucketnames: ${S3_NAME}

compactor:
  retention_enabled: true
  working_directory: /tmp/compactor
  delete_request_store: s3
