[package]
name = "common"
version = "0.1.0"
edition = "2024"
resolver = "3"
[dependencies]
chrono = { workspace = true }
chrono-tz = { workspace = true }
maplit = "1.0.2"
once_cell = "1.21.3"
tracing = { workspace = true }
